name: On Issue Creation
run-name: An issue was opened by ${{ github.actor }} 

on: issues

jobs:
  greet-new-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new issue
        run: echo "ðŸŽ‰ An issue with title '${{ github.event.issue.title }}' was created!"
